# Generated by Django 3.2.12 on 2022-05-23 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('adult', models.BooleanField()),
                ('backdrop_path', models.CharField(max_length=200, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('original_language', models.CharField(max_length=20)),
                ('original_title', models.CharField(max_length=100)),
                ('overview', models.CharField(max_length=200, null=True)),
                ('popularity', models.FloatField()),
                ('poster_path', models.CharField(max_length=200, null=True)),
                ('release_date', models.DateField()),
                ('revenue', models.IntegerField()),
                ('runtime', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('Rumored', 'Rumored'), ('Planned', 'Planned'), ('In Production', 'In Production'), ('Post Production', 'Post Production'), ('Released', 'Released'), ('Canceled', 'Canceled')], max_length=20)),
                ('tagline', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200)),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('genres', models.ManyToManyField(related_name='genre_movies', to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCompany',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('logo_path', models.CharField(max_length=100, null=True)),
                ('origin_country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_3166_1', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SpokenLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_639_1', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='production_companies',
            field=models.ManyToManyField(related_name='production_movies', to='movies.ProductionCompany'),
        ),
        migrations.AddField(
            model_name='movie',
            name='production_countries',
            field=models.ManyToManyField(related_name='production_movies', to='movies.ProductionCountry'),
        ),
        migrations.AddField(
            model_name='movie',
            name='spoken_languages',
            field=models.ManyToManyField(related_name='movies', to='movies.SpokenLanguage'),
        ),
        migrations.AddField(
            model_name='movie',
            name='voted_users',
            field=models.ManyToManyField(through='movies.Vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='wishing_users',
            field=models.ManyToManyField(related_name='wished_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('movies', models.ManyToManyField(related_name='keywords', to='movies.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('adult', models.BooleanField()),
                ('gender', models.IntegerField(null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('original_name', models.CharField(max_length=100)),
                ('popularity', models.FloatField()),
                ('profile_path', models.CharField(max_length=100, null=True)),
                ('character', models.CharField(max_length=100)),
                ('movies', models.ManyToManyField(related_name='actors', to='movies.Movie')),
            ],
        ),
    ]
