# Generated by Django 3.2.12 on 2022-05-24 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_auto_20220524_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='voted_users',
            field=models.ManyToManyField(through='movies.Vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='wishing_users',
            field=models.ManyToManyField(related_name='wished_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
