# Generated by Django 3.2.12 on 2022-05-26 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20220525_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='movies.movie'),
        ),
    ]
