# Generated by Django 3.2.12 on 2022-05-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_vote_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='score',
            field=models.IntegerField(),
        ),
    ]
