# Generated by Django 3.2.12 on 2022-05-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewcomment',
            old_name='article',
            new_name='review',
        ),
    ]
